import { ArrowRight, CheckCircle2, Search, ShieldCheck, Sparkles, Star, Users, Video } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const fallbackCourses=[
{id:'1',title:'Graphic Design Complete Course',description:'Baro Photoshop, Illustrator iyo InDesign.',discounted_price:0,original_price:0},
{id:'2',title:'Video Editing with CapCut',description:'Ka baro tafatirka muuqaalka ilaa heer xirfadeed.',discounted_price:0,original_price:0},
{id:'3',title:'Artificial Intelligence A-Z',description:'Faham AI, prompts iyo content creation.',discounted_price:0,original_price:0},
{id:'4',title:'Web Development',description:'Dhis websites casri ah oo responsive ah.',discounted_price:0,original_price:0},
];
type HomeSettings={tagline:string;heroTitle:string;heroHighlight:string;heroDescription:string;primaryCta:string;secondaryCta:string;students:string;courses:string;instructors:string;satisfaction:string;contactEmail:string};
const defaults:HomeSettings={tagline:'Ku Baro. Ku Kobco. Ku Guuleyso.',heroTitle:'Xirfad Maal',heroHighlight:'Academy',heroDescription:'Baro xirfado casri ah oo aad mustaqbalkaaga ku dhisi karto. Waxbarasho online ah oo tayo leh, casharro la taaban karo iyo macallimiin khibrad leh.',primaryCta:'Bilow Hadda',secondaryCta:'Daawo Courses',students:'500+',courses:'50+',instructors:'20+',satisfaction:'100%',contactEmail:'register@xirfadmaal.com'};
async function getContent(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return defaults;const sb=createClient(url,key);const{data}=await sb.from('settings').select('value').eq('key','homepage').maybeSingle();return data?.value?{...defaults,...(data.value as Partial<HomeSettings>)}:defaults;}
async function getCourses(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return fallbackCourses;const sb=createClient(url,key);const{data}=await sb.from('courses').select('id,title,description,discounted_price,original_price').order('created_at',{ascending:false}).limit(8);return data?.length?data:fallbackCourses;}
function Logo(){return <a href="/" className="brand"><span className="brand-mark">✦</span><span><b>Xirfad Maal</b><small>ACADEMY</small></span></a>}
export default async function Home(){const[courses,content]=await Promise.all([getCourses(),getContent()]);return <main className="site-shell">
<header className="nav"><div className="container nav-inner"><Logo/><nav className="links"><a className="active" href="/">Home</a><a href="#courses">Courses</a><a href="#why">Why Us</a><a href="#about">About Us</a><a href="#contact">Contact</a></nav><div className="actions"><button className="icon-btn" aria-label="Search"><Search size={18}/></button><span className="lang-pill">◎ EN</span><a className="btn btn-primary" href="/login">Login</a></div></div></header>
<section className="hero-ref"><div className="container hero-ref-grid"><div className="hero-copy"><span className="eyebrow"><Sparkles size={13}/> {content.tagline}</span><h1>{content.heroTitle}<br/><span>{content.heroHighlight}</span></h1><p>{content.heroDescription}</p><div className="hero-actions"><a className="btn btn-primary btn-lg" href="/register">{content.primaryCta} <ArrowRight size={18}/></a><a className="btn btn-outline btn-lg" href="#courses">{content.secondaryCta}</a></div><div className="hero-stats"><div><strong>{content.students}</strong><span>Arday</span></div><div><strong>{content.courses}</strong><span>Courses</span></div><div><strong>{content.instructors}</strong><span>Instructors</span></div><div><strong>{content.satisfaction}</strong><span>Satisfaction</span></div></div></div><div className="hero-art" aria-hidden="true"><div className="orb orb-one"/><div className="orb orb-two"/><div className="glow-person"><div className="person-head"/><div className="person-body"/><div className="laptop"/><div className="person-arm"/></div><div className="float-card float-play">▶</div><div className="float-card float-cap">⌂</div><div className="float-card float-chart">↗</div><div className="art-label"><b>Baro</b><span>Xirfado Cusub</span></div></div></div></section>
<section className="search-strip"><div className="container search-panel"><div><b>Raadi Course ku Habboon</b><span>Dhammaan xirfadaha hal meel.</span></div><div className="search-fields"><label><Search size={17}/><input placeholder="Raadi course..."/></label><select defaultValue=""><option value="">Dhammaan Kategoriyada</option><option>Design</option><option>Technology</option><option>Marketing</option></select><a className="btn btn-primary" href="/courses">Raadi Course</a></div></div></section>
<section id="courses" className="section light-section"><div className="container"><div className="section-head"><div><span className="section-kicker">LEARN & GROW</span><h2>Courses <span>Popular ah</span></h2></div><a className="section-link" href="/courses">Dhammaan Courses <ArrowRight size={16}/></a></div><div className="course-grid-ref">{courses.slice(0,4).map((course,index)=><article className="course-ref" key={course.id}><div className={'course-image ci-'+index}><span>{index===0?'Ps':index===1?'CE':index===2?'Ai':'WEB'}</span><em>{index<2?'Popular':'New'}</em></div><div className="course-body-ref"><div className="course-meta">Fudud · {30+index*5} Lessons</div><h3>{course.title}</h3><div className="rating"><Star size={14} fill="currentColor"/> 4.{9-index} <span>({60+index*28})</span></div><div className="course-foot"><strong>{Number(course.discounted_price??0)===0?'Free':`$${course.discounted_price}`}</strong><a href={`/courses/${course.id}`}>Eeg <ArrowRight size={14}/></a></div></div></article>)}</div></div></section>
<section id="why" className="benefit-section"><div className="container benefit-grid"><div><span className="section-kicker">WHY XIRFAD MAAL</span><h2>Waxbarasho kuu dhisan,<br/><span>mustaqbal kuu dhisan.</span></h2><p className="muted">Waxaan isku keenaynaa casharro tayo leh, macallimiin khibrad leh iyo LMS kuu oggolaanaya inaad wax barato meel kasta.</p></div><div className="benefit-cards"><div><Video/><b>Online Classes</b><span>24/7 access to quality education</span></div><div><Users/><b>Expert Instructors</b><span>Learn from industry professionals</span></div><div><CheckCircle2/><b>Certificate</b><span>Get certified and boost your career</span></div><div><ShieldCheck/><b>Secure & Fast</b><span>Your data is safe with us</span></div></div></div></section>
<section id="about" className="cta-ref"><div className="container cta-inner"><div><span className="eyebrow">READY TO START?</span><h2>Diyaar ma u tahay xirfaddaada cusub?</h2><p>Ku biir Xirfad Maal Academy maanta.</p></div><a className="btn btn-primary btn-lg" href="/register">{content.primaryCta} <ArrowRight size={18}/></a></div></section>
<footer id="contact" className="footer"><div className="container footer-inner"><Logo/><span>© {new Date().getFullYear()} Xirfad Maal Academy.</span><a href={`mailto:${content.contactEmail}`}>{content.contactEmail}</a></div></footer>
</main>}
