'use client';
import { useEffect,useState } from 'react';
import { ArrowLeft,Award,Save,RotateCcw,ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { createClient } from '@supabase/supabase-js';
import './certificates.css';

type Settings={academy_name:string;logo_url:string;certificate_title:string;signature_name:string;signature_title:string;signature_image_url:string;certificate_wording:string;branding_color:string;accent_color:string};
const defaults:Settings={academy_name:'Xirfad Maal Academy',logo_url:'',certificate_title:'Certificate of Completion',signature_name:'Academy Director',signature_title:'Director',signature_image_url:'',certificate_wording:'This certificate is proudly presented for successfully completing the course.',branding_color:'#173c88',accent_color:'#d7ad3f'};
export default function AdminCertificates(){const [form,setForm]=useState(defaults),[saved,setSaved]=useState(defaults),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[authorized,setAuthorized]=useState<boolean|null>(null);const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){location.href='/login';return;}const {data:p}=await sb.from('profiles').select('role').eq('id',user.id).single();if(!['ADMIN','OWNER'].includes(p?.role)){setAuthorized(false);return;}setAuthorized(true);const {data}=await sb.from('certificate_settings').select('*').eq('id',1).maybeSingle();if(data){const s={...defaults,...data};setForm(s);setSaved(s)}})()},[]);
 async function save(){setSaving(true);setMsg('');const {error}=await sb.rpc('update_certificate_settings',{p_academy_name:form.academy_name,p_logo_url:form.logo_url,p_certificate_title:form.certificate_title,p_signature_name:form.signature_name,p_signature_title:form.signature_title,p_signature_image_url:form.signature_image_url,p_certificate_wording:form.certificate_wording,p_branding_color:form.branding_color,p_accent_color:form.accent_color});if(error)setMsg(error.message);else{setSaved(form);setMsg('Certificate settings waa la kaydiyey.')}setSaving(false)}
 if(authorized===null)return <main className="ac-loading">Loading Certificate Center...</main>;if(!authorized)return <main className="ac-loading">Access denied.</main>;
 const set=(key:keyof Settings,value:string)=>setForm(f=>({...f,[key]:value}));
 return <main className="ac-page"><header className="ac-head"><Link href="/admin"><ArrowLeft size={18}/> Admin</Link><div><span>CERTIFICATE CENTER</span><h1>Certificate Settings</h1><p>Maamul design-ka certificate-ka oo arag preview-ga isla waqtigaas.</p></div><button className="ac-save" onClick={save} disabled={saving}><Save size={17}/>{saving?'Saving...':'Save Changes'}</button></header><div className="ac-layout"><section className="ac-editor"><h2>Design & Content</h2><label>Academy Name<input value={form.academy_name} onChange={e=>set('academy_name',e.target.value)}/></label><label>Certificate Title<input value={form.certificate_title} onChange={e=>set('certificate_title',e.target.value)}/></label><label>Certificate Wording<textarea rows={4} value={form.certificate_wording} onChange={e=>set('certificate_wording',e.target.value)}/></label><div className="ac-two"><label>Brand Color<input type="color" value={form.branding_color} onChange={e=>set('branding_color',e.target.value)}/></label><label>Accent Color<input type="color" value={form.accent_color} onChange={e=>set('accent_color',e.target.value)}/></label></div><label>Logo URL<input value={form.logo_url} onChange={e=>set('logo_url',e.target.value)} placeholder="https://..."/></label><div className="ac-two"><label>Signature Name<input value={form.signature_name} onChange={e=>set('signature_name',e.target.value)}/></label><label>Signature Title<input value={form.signature_title} onChange={e=>set('signature_title',e.target.value)}/></label></div><label>Signature Image URL<input value={form.signature_image_url} onChange={e=>set('signature_image_url',e.target.value)} placeholder="https://..."/></label>{msg&&<div className="ac-msg">{msg}</div>}<button className="ac-reset" onClick={()=>setForm(saved)}><RotateCcw size={15}/> Reset unsaved changes</button></section><section className="ac-preview"><div className="preview-top"><div><span>LIVE PREVIEW</span><h2>Certificate</h2></div><ShieldCheck size={20}/></div><div className="paper" style={{borderColor:form.branding_color}}><div className="paper-inner" style={{borderColor:form.accent_color}}>{form.logo_url?<img src={form.logo_url} alt="Logo"/>:<div className="logo-fallback" style={{color:form.branding_color}}><Award size={28}/></div>}<b style={{color:form.branding_color}}>{form.academy_name}</b><small>OFFICIAL CERTIFICATE</small><h3 style={{color:form.branding_color}}>{form.certificate_title}</h3><p>{form.certificate_wording}</p><div className="masked-name">••••••••••••••••</div><span className="masked-label">Student name hidden until course completion</span><div className="preview-course">Course: •••••••••••</div><div className="paper-footer"><span>Signature<br/><strong>{form.signature_name}</strong><small>{form.signature_title}</small></span>{form.signature_image_url&&<img src={form.signature_image_url} alt="Signature"/>}<span>Verification ID<br/><strong>SHU-••••••-••••</strong></span></div></div></div></section></div></main>;
}
