'use client';
import { useEffect, useMemo, useState } from 'react';
import { Search, Users, UserCheck, Mail, ShieldCheck, ArrowLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { createClient } from '@supabase/supabase-js';
import '../admin.css';
import './students.css';

type Row={id:string;full_name:string|null;display_name:string|null;email:string;role:string;created_at:string};
export default function StudentsPage(){const router=useRouter();const[rows,setRows]=useState<Row[]>([]);const[q,setQ]=useState('');const[loading,setLoading]=useState(true);const[allowed,setAllowed]=useState<boolean|null>(null);
 const sb=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
 useEffect(()=>{(async()=>{const s=sb();const{data:a}=await s.auth.getUser();if(!a.user){router.replace('/login');return;}const{data:p}=await s.from('profiles').select('role').eq('id',a.user.id).single();if(!['ADMIN','OWNER'].includes(p?.role)){setAllowed(false);setLoading(false);return;}setAllowed(true);const{data}=await s.from('profiles').select('id,full_name,display_name,email,role,created_at').order('created_at',{ascending:false});setRows(data??[]);setLoading(false)})()},[router]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.full_name??''} ${r.display_name??''} ${r.email}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 if(loading)return <main className="admin-loading"><div className="admin-loader">Ardayda waa la soo gelinayaa...</div></main>;if(!allowed)return <main className="section"><div className="container"><div className="hero-card"><h2>Maamulka waa xiran yahay</h2></div></div></main>;
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span className="brand-mark">✦</span><span><b>Xirfad Maal</b><small>ACADEMY</small></span></div><nav className="admin-menu"><a href="/admin">Dashboard</a><a className="selected" href="/admin/students">Students</a><a href="/admin/courses">Courses</a><a href="/admin/website">Website Editor</a></nav></aside><section className="admin-main"><header className="admin-top"><div><a className="admin-back" href="/admin"><ArrowLeft size={15}/> Dashboard</a><span className="section-kicker">STUDENT MANAGEMENT</span><h1>Ardayda</h1><p>Maamul oo raadi dadka isticmaala academy-ga.</p></div></header><div className="student-admin-stats"><div><Users size={20}/><b>{rows.length}</b><span>Users</span></div><div><UserCheck size={20}/><b>{rows.filter(r=>r.role==='STUDENT').length}</b><span>Students</span></div><div><ShieldCheck size={20}/><b>{rows.filter(r=>['ADMIN','OWNER','INSTRUCTOR'].includes(r.role)).length}</b><span>Staff</span></div></div><section className="admin-panel student-admin-panel"><div className="student-toolbar"><div><h2>All Users</h2><p>{filtered.length} natiijo</p></div><div className="student-search"><Search size={16}/><input placeholder="Raadi magaca ama email..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="student-table">{filtered.map(r=><article key={r.id}><div className="student-avatar-admin">{(r.full_name||r.display_name||r.email||'U').slice(0,1).toUpperCase()}</div><div className="student-person"><b>{r.full_name||r.display_name||'Magac lama gelin'}</b><span><Mail size={12}/>{r.email}</span></div><span className={`role role-${r.role.toLowerCase()}`}>{r.role}</span><time>{new Date(r.created_at).toLocaleDateString()}</time></article>)}{!filtered.length&&<div className="student-no-results">Lama helin user ku habboon raadinta.</div>}</div></section></section></main>}
