'use client';

import '../admin.css';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, Globe2, Save, Sparkles } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

type HomeSettings = { tagline:string;heroTitle:string;heroHighlight:string;heroDescription:string;primaryCta:string;secondaryCta:string;students:string;courses:string;instructors:string;satisfaction:string;contactEmail:string };
const defaults:HomeSettings={tagline:'Ku Baro. Ku Kobco. Ku Guuleyso.',heroTitle:'Xirfad Maal',heroHighlight:'Academy',heroDescription:'Baro xirfado casri ah oo aad mustaqbalkaaga ku dhisi karto. Waxbarasho online ah oo tayo leh, casharro la taaban karo iyo macallimiin khibrad leh.',primaryCta:'Bilow Hadda',secondaryCta:'Daawo Courses',students:'500+',courses:'50+',instructors:'20+',satisfaction:'100%',contactEmail:'register@xirfadmaal.com'};
export default function WebsiteEditor(){const router=useRouter();const[form,setForm]=useState(defaults);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{(async()=>{const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);const{data:{user}}=await sb.auth.getUser();if(!user){router.replace('/login');return;}const{data:p}=await sb.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='ADMIN'&&p?.role!=='OWNER'){router.replace('/dashboard');return;}const{data}=await sb.from('settings').select('value').eq('key','homepage').maybeSingle();if(data?.value)setForm({...defaults,...(data.value as Partial<HomeSettings>)});setLoading(false);})();},[router]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setSaved(false);setError('');const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);const{error}=await sb.from('settings').upsert({key:'homepage',value:form},{onConflict:'key'});if(error)setError(error.message);else setSaved(true);setSaving(false);}
 if(loading)return <main className="admin-loading"><div className="admin-loader">Loading website editor...</div></main>;
 const field=(key:keyof HomeSettings,label:string,wide=false)=><label className={wide?'website-field website-wide':'website-field'}><span>{label}</span>{wide?<textarea rows={4} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>;
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span className="brand-mark">✦</span><span><b>Xirfad Maal</b><small>ACADEMY</small></span></div><nav className="admin-menu"><a href="/admin">Dashboard</a><a className="selected" href="/admin/website"><Globe2 size={16}/> Website Editor</a><a href="/admin">Courses</a><a href="/admin">Students</a><a href="/admin">Settings</a></nav></aside><section className="admin-main"><header className="admin-top"><div><span className="section-kicker">VISUAL CONTENT CONTROL</span><h1>Website Editor</h1><p>Wax ka beddel homepage-ka adigoon code taaban.</p></div><a className="btn btn-primary" href="/"><Globe2 size={16}/> Arag Website-ka</a></header><section className="website-editor-card"><div className="website-editor-head"><div className="editor-icon"><Sparkles size={18}/></div><h2>Homepage Content</h2><p>Qoraallada hoose waa editable, waxaana si joogto ah loogu kaydinayaa Supabase.</p></div><form onSubmit={save} className="website-form"><div className="website-grid">{field('tagline','Tagline')}{field('heroTitle','Hero title')}{field('heroHighlight','Hero highlight')}{field('primaryCta','Primary button')}{field('secondaryCta','Secondary button')}{field('contactEmail','Contact email')}{field('students','Arday statistic')}{field('courses','Courses statistic')}{field('instructors','Instructors statistic')}{field('satisfaction','Satisfaction statistic')}{field('heroDescription','Hero description',true)}</div>{error&&<p className="form-error">{error}</p>}{saved&&<p className="save-success"><Check size={15}/> Isbeddelka waa la kaydiyey.</p>}<button className="btn btn-primary btn-lg" disabled={saving}><Save size={16}/>{saving?'Kaydinaya...':'Kaydi Isbeddelada'}</button></form></section></section></main>}
