'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Edit3, Plus, Search, Trash2, UserRound, X } from 'lucide-react';
import Link from 'next/link';
import { createClient } from '@supabase/supabase-js';
import './instructors.css';

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Instructor = { id:string; name:string; bio:string; avatar_url:string; specialty:string; created_at:string; courseCount?:number };
type CourseRef = { instructor_id:string|null };

export default function InstructorsAdmin(){
 const [items,setItems]=useState<Instructor[]>([]),[search,setSearch]=useState(''),[editing,setEditing]=useState<Instructor|null>(null),[modalOpen,setModalOpen]=useState(false),[form,setForm]=useState({name:'',bio:'',avatar_url:'',specialty:''}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function guard(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/login';return false}const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).single();if(!p||!['ADMIN','OWNER'].includes(p.role)){window.location.href='/dashboard';return false}return true}
 async function load(){setLoading(true);const [{data:ins,error:ie},{data:crs,error:ce}]=await Promise.all([supabase.from('instructors').select('*').order('created_at',{ascending:true}),supabase.from('courses').select('instructor_id')]);if(ie||ce)setError(ie?.message||ce?.message||'Failed to load instructors.');const refs=(crs||[]) as CourseRef[];setItems(((ins||[]) as Instructor[]).map(i=>({...i,courseCount:refs.filter(r=>r.instructor_id===i.id).length})));setLoading(false)}
 useEffect(()=>{guard().then(ok=>ok&&load())},[]);
 const filtered=useMemo(()=>items.filter(i=>`${i.name} ${i.specialty} ${i.bio}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 function openCreate(){setEditing(null);setForm({name:'',bio:'',avatar_url:'',specialty:''});setError('');setModalOpen(true)}
 function openEdit(i:Instructor){setEditing(i);setForm({name:i.name||'',bio:i.bio||'',avatar_url:i.avatar_url||'',specialty:i.specialty||''});setError('');setModalOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!form.name.trim()){setError('Instructor name is required.');return}setSaving(true);setError('');const payload={name:form.name.trim(),bio:form.bio.trim(),avatar_url:form.avatar_url.trim(),specialty:form.specialty.trim()};const r=editing?await supabase.from('instructors').update(payload).eq('id',editing.id):await supabase.from('instructors').insert(payload);if(r.error)setError(r.error.message);else{setModalOpen(false);await load()}setSaving(false)}
 async function remove(i:Instructor){if((i.courseCount||0)>0){setError(`“${i.name}” is assigned to ${i.courseCount} course(s). Reassign those courses first.`);return}if(!window.confirm(`Delete instructor “${i.name}”?`))return;const {error:e}=await supabase.from('instructors').delete().eq('id',i.id);if(e)setError(e.message);else load()}
 return <main className="instructor-page"><header className="instructor-topbar"><Link href="/admin" className="back-link"><ArrowLeft size={18}/> Admin Dashboard</Link><div><span className="eyebrow">PEOPLE MANAGEMENT</span><h1>Instructors</h1><p>Manage the experts who teach your academy.</p></div><button className="primary-btn" onClick={openCreate}><Plus size={18}/> New Instructor</button></header><section className="instructor-shell"><div className="instructor-toolbar"><div className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search instructors..."/></div><span>{filtered.length} instructors</span></div>{error&&<div className="error-box">{error}</div>}{loading?<div className="empty-state">Loading instructors...</div>:filtered.length===0?<div className="empty-state"><UserRound size={36}/><strong>No instructors found</strong><span>Add an instructor to start assigning courses.</span></div>:<div className="instructor-grid">{filtered.map(i=><article className="instructor-card" key={i.id}><div className="instructor-avatar">{i.avatar_url?<img src={i.avatar_url} alt=""/>:<UserRound size={28}/>}</div><div className="instructor-content"><h2>{i.name}</h2><span className="specialty">{i.specialty||'Instructor'}</span><p>{i.bio||'No bio added yet.'}</p><div className="course-count">{i.courseCount||0} course{(i.courseCount||0)===1?'':'s'}</div></div><div className="instructor-actions"><button onClick={()=>openEdit(i)} aria-label="Edit"><Edit3 size={17}/></button><button onClick={()=>remove(i)} aria-label="Delete"><Trash2 size={17}/></button></div></article>)}</div>}</section>{modalOpen&&<div className="modal-backdrop" onMouseDown={()=>setModalOpen(false)}><div className="instructor-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModalOpen(false)}><X size={20}/></button><span className="eyebrow">{editing?'EDIT INSTRUCTOR':'NEW INSTRUCTOR'}</span><h2>{editing?'Update instructor':'Create instructor'}</h2><form onSubmit={save}><label>Name<input autoFocus value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="Ahmed Ali"/></label><label>Specialty<input value={form.specialty} onChange={e=>setForm(f=>({...f,specialty:e.target.value}))} placeholder="Graphic Design"/></label><label>Avatar URL<input value={form.avatar_url} onChange={e=>setForm(f=>({...f,avatar_url:e.target.value}))} placeholder="https://..."/></label><label>Bio<textarea value={form.bio} onChange={e=>setForm(f=>({...f,bio:e.target.value}))} placeholder="Short instructor bio..." rows={4}/></label><button className="primary-btn save-btn" disabled={saving}>{saving?'Saving...':editing?'Save Changes':'Create Instructor'}</button></form></div></div>}</main>;
}
